name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
            
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR
